// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: proto/userservice/user_service.proto

package userproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url       string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Width     int32  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height    int32  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	CloudName string `protobuf:"bytes,5,opt,name=cloudName,proto3" json:"cloudName,omitempty"`
	Extension string `protobuf:"bytes,6,opt,name=extension,proto3" json:"extension,omitempty"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userservice_user_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userservice_user_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_proto_userservice_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Image) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Image) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Image) GetCloudName() string {
	if x != nil {
		return x.CloudName
	}
	return ""
}

func (x *Image) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

type Settings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Theme    string `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *Settings) Reset() {
	*x = Settings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userservice_user_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userservice_user_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_proto_userservice_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *Settings) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *Settings) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type UserUpdateProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int32     `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Phone    string    `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Name     string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Avatar   *Image    `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Settings *Settings `protobuf:"bytes,5,opt,name=settings,proto3" json:"settings,omitempty"`
}

func (x *UserUpdateProfileRequest) Reset() {
	*x = UserUpdateProfileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userservice_user_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateProfileRequest) ProtoMessage() {}

func (x *UserUpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userservice_user_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UserUpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_userservice_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *UserUpdateProfileRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserUpdateProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserUpdateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserUpdateProfileRequest) GetAvatar() *Image {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *UserUpdateProfileRequest) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UserUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Image  *Image `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *UserUploadRequest) Reset() {
	*x = UserUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userservice_user_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUploadRequest) ProtoMessage() {}

func (x *UserUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userservice_user_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUploadRequest.ProtoReflect.Descriptor instead.
func (*UserUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_userservice_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *UserUploadRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserUploadRequest) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type UserUpdatePasswordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int32  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *UserUpdatePasswordRequest) Reset() {
	*x = UserUpdatePasswordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userservice_user_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdatePasswordRequest) ProtoMessage() {}

func (x *UserUpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userservice_user_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UserUpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_userservice_user_service_proto_rawDescGZIP(), []int{4}
}

func (x *UserUpdatePasswordRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserUpdatePasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserUpdateDeviceTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	DeviceTokens []string `protobuf:"bytes,2,rep,name=deviceTokens,proto3" json:"deviceTokens,omitempty"`
}

func (x *UserUpdateDeviceTokenRequest) Reset() {
	*x = UserUpdateDeviceTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userservice_user_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUpdateDeviceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateDeviceTokenRequest) ProtoMessage() {}

func (x *UserUpdateDeviceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userservice_user_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateDeviceTokenRequest.ProtoReflect.Descriptor instead.
func (*UserUpdateDeviceTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_userservice_user_service_proto_rawDescGZIP(), []int{5}
}

func (x *UserUpdateDeviceTokenRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserUpdateDeviceTokenRequest) GetDeviceTokens() []string {
	if x != nil {
		return x.DeviceTokens
	}
	return nil
}

type UserUpdateProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         int32     `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Email          string    `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone          string    `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Name           string    `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	FbId           string    `protobuf:"bytes,5,opt,name=fbId,proto3" json:"fbId,omitempty"`
	GgId           string    `protobuf:"bytes,6,opt,name=ggId,proto3" json:"ggId,omitempty"`
	Salt           string    `protobuf:"bytes,7,opt,name=salt,proto3" json:"salt,omitempty"`
	Avatar         *Image    `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Level          int32     `protobuf:"varint,9,opt,name=level,proto3" json:"level,omitempty"`
	Experience     int32     `protobuf:"varint,10,opt,name=experience,proto3" json:"experience,omitempty"`
	Settings       *Settings `protobuf:"bytes,11,opt,name=settings,proto3" json:"settings,omitempty"`
	Role           string    `protobuf:"bytes,12,opt,name=role,proto3" json:"role,omitempty"`
	HabitCount     int32     `protobuf:"varint,13,opt,name=habitCount,proto3" json:"habitCount,omitempty"`
	TaskCount      int32     `protobuf:"varint,14,opt,name=taskCount,proto3" json:"taskCount,omitempty"`
	ChallengeCount int32     `protobuf:"varint,15,opt,name=challengeCount,proto3" json:"challengeCount,omitempty"`
	Status         int32     `protobuf:"varint,16,opt,name=status,proto3" json:"status,omitempty"`
	DeviceTokens   []string  `protobuf:"bytes,17,rep,name=deviceTokens,proto3" json:"deviceTokens,omitempty"`
}

func (x *UserUpdateProfileResponse) Reset() {
	*x = UserUpdateProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userservice_user_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateProfileResponse) ProtoMessage() {}

func (x *UserUpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userservice_user_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UserUpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_userservice_user_service_proto_rawDescGZIP(), []int{6}
}

func (x *UserUpdateProfileResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserUpdateProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserUpdateProfileResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserUpdateProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserUpdateProfileResponse) GetFbId() string {
	if x != nil {
		return x.FbId
	}
	return ""
}

func (x *UserUpdateProfileResponse) GetGgId() string {
	if x != nil {
		return x.GgId
	}
	return ""
}

func (x *UserUpdateProfileResponse) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *UserUpdateProfileResponse) GetAvatar() *Image {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *UserUpdateProfileResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserUpdateProfileResponse) GetExperience() int32 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *UserUpdateProfileResponse) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *UserUpdateProfileResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserUpdateProfileResponse) GetHabitCount() int32 {
	if x != nil {
		return x.HabitCount
	}
	return 0
}

func (x *UserUpdateProfileResponse) GetTaskCount() int32 {
	if x != nil {
		return x.TaskCount
	}
	return 0
}

func (x *UserUpdateProfileResponse) GetChallengeCount() int32 {
	if x != nil {
		return x.ChallengeCount
	}
	return 0
}

func (x *UserUpdateProfileResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserUpdateProfileResponse) GetDeviceTokens() []string {
	if x != nil {
		return x.DeviceTokens
	}
	return nil
}

type UserUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image *Image `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *UserUploadResponse) Reset() {
	*x = UserUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userservice_user_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUploadResponse) ProtoMessage() {}

func (x *UserUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userservice_user_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUploadResponse.ProtoReflect.Descriptor instead.
func (*UserUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_userservice_user_service_proto_rawDescGZIP(), []int{7}
}

func (x *UserUploadResponse) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type UserUpdatePasswordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	IsDone bool  `protobuf:"varint,2,opt,name=isDone,proto3" json:"isDone,omitempty"`
}

func (x *UserUpdatePasswordResponse) Reset() {
	*x = UserUpdatePasswordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userservice_user_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUpdatePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdatePasswordResponse) ProtoMessage() {}

func (x *UserUpdatePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userservice_user_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdatePasswordResponse.ProtoReflect.Descriptor instead.
func (*UserUpdatePasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_userservice_user_service_proto_rawDescGZIP(), []int{8}
}

func (x *UserUpdatePasswordResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserUpdatePasswordResponse) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

type UserUpdateDeviceTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	IsDone bool  `protobuf:"varint,2,opt,name=isDone,proto3" json:"isDone,omitempty"`
}

func (x *UserUpdateDeviceTokenResponse) Reset() {
	*x = UserUpdateDeviceTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userservice_user_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUpdateDeviceTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateDeviceTokenResponse) ProtoMessage() {}

func (x *UserUpdateDeviceTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userservice_user_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateDeviceTokenResponse.ProtoReflect.Descriptor instead.
func (*UserUpdateDeviceTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_userservice_user_service_proto_rawDescGZIP(), []int{9}
}

func (x *UserUpdateDeviceTokenResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserUpdateDeviceTokenResponse) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

var File_proto_userservice_user_service_proto protoreflect.FileDescriptor

var file_proto_userservice_user_service_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x62, 0x65, 0x73, 0x74, 0x48, 0x61, 0x62, 0x69,
	0x74, 0x22, 0x93, 0x01, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x74,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x78,
	0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3c, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x22, 0xb7, 0x01, 0x0a, 0x18, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x65, 0x73, 0x74, 0x48, 0x61, 0x62, 0x69, 0x74,
	0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x2f,
	0x0a, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x62, 0x65, 0x73, 0x74, 0x48, 0x61, 0x62, 0x69, 0x74, 0x2e, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22,
	0x53, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x65,
	0x73, 0x74, 0x48, 0x61, 0x62, 0x69, 0x74, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x22, 0x4f, 0x0a, 0x19, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x5a, 0x0a, 0x1c, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a,
	0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x73, 0x22, 0xf6, 0x03, 0x0a, 0x19, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x62, 0x49, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x62, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x67,
	0x67, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x67, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73,
	0x61, 0x6c, 0x74, 0x12, 0x28, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x65, 0x73, 0x74, 0x48, 0x61, 0x62, 0x69, 0x74, 0x2e,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63,
	0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x65, 0x73, 0x74, 0x48, 0x61, 0x62, 0x69,
	0x74, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x61, 0x62, 0x69,
	0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x68, 0x61,
	0x62, 0x69, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x61, 0x73,
	0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65,
	0x6e, 0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e,
	0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x11, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x22, 0x3c, 0x0a, 0x12, 0x55, 0x73,
	0x65, 0x72, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x26, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x62, 0x65, 0x73, 0x74, 0x48, 0x61, 0x62, 0x69, 0x74, 0x2e, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x4c, 0x0a, 0x1a, 0x55, 0x73, 0x65, 0x72,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x69, 0x73, 0x44, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x69, 0x73, 0x44, 0x6f, 0x6e, 0x65, 0x22, 0x4f, 0x0a, 0x1d, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x69, 0x73, 0x44, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x69, 0x73, 0x44, 0x6f, 0x6e, 0x65, 0x32, 0x8f, 0x03, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x23, 0x2e, 0x62,
	0x65, 0x73, 0x74, 0x48, 0x61, 0x62, 0x69, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x62, 0x65, 0x73, 0x74, 0x48, 0x61, 0x62, 0x69, 0x74, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0a, 0x55, 0x73, 0x65,
	0x72, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1c, 0x2e, 0x62, 0x65, 0x73, 0x74, 0x48, 0x61,
	0x62, 0x69, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x62, 0x65, 0x73, 0x74, 0x48, 0x61, 0x62, 0x69,
	0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x24, 0x2e, 0x62,
	0x65, 0x73, 0x74, 0x48, 0x61, 0x62, 0x69, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x62, 0x65, 0x73, 0x74, 0x48, 0x61, 0x62, 0x69, 0x74, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6c, 0x0a, 0x15, 0x55,
	0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x27, 0x2e, 0x62, 0x65, 0x73, 0x74, 0x48, 0x61, 0x62, 0x69, 0x74,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x62, 0x65, 0x73, 0x74, 0x48, 0x61, 0x62, 0x69, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x75, 0x73, 0x65,
	0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_userservice_user_service_proto_rawDescOnce sync.Once
	file_proto_userservice_user_service_proto_rawDescData = file_proto_userservice_user_service_proto_rawDesc
)

func file_proto_userservice_user_service_proto_rawDescGZIP() []byte {
	file_proto_userservice_user_service_proto_rawDescOnce.Do(func() {
		file_proto_userservice_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_userservice_user_service_proto_rawDescData)
	})
	return file_proto_userservice_user_service_proto_rawDescData
}

var file_proto_userservice_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_userservice_user_service_proto_goTypes = []interface{}{
	(*Image)(nil),                         // 0: bestHabit.Image
	(*Settings)(nil),                      // 1: bestHabit.Settings
	(*UserUpdateProfileRequest)(nil),      // 2: bestHabit.UserUpdateProfileRequest
	(*UserUploadRequest)(nil),             // 3: bestHabit.UserUploadRequest
	(*UserUpdatePasswordRequest)(nil),     // 4: bestHabit.UserUpdatePasswordRequest
	(*UserUpdateDeviceTokenRequest)(nil),  // 5: bestHabit.UserUpdateDeviceTokenRequest
	(*UserUpdateProfileResponse)(nil),     // 6: bestHabit.UserUpdateProfileResponse
	(*UserUploadResponse)(nil),            // 7: bestHabit.UserUploadResponse
	(*UserUpdatePasswordResponse)(nil),    // 8: bestHabit.UserUpdatePasswordResponse
	(*UserUpdateDeviceTokenResponse)(nil), // 9: bestHabit.UserUpdateDeviceTokenResponse
}
var file_proto_userservice_user_service_proto_depIdxs = []int32{
	0,  // 0: bestHabit.UserUpdateProfileRequest.avatar:type_name -> bestHabit.Image
	1,  // 1: bestHabit.UserUpdateProfileRequest.settings:type_name -> bestHabit.Settings
	0,  // 2: bestHabit.UserUploadRequest.image:type_name -> bestHabit.Image
	0,  // 3: bestHabit.UserUpdateProfileResponse.avatar:type_name -> bestHabit.Image
	1,  // 4: bestHabit.UserUpdateProfileResponse.settings:type_name -> bestHabit.Settings
	0,  // 5: bestHabit.UserUploadResponse.image:type_name -> bestHabit.Image
	2,  // 6: bestHabit.UserService.UserUpdateProfile:input_type -> bestHabit.UserUpdateProfileRequest
	3,  // 7: bestHabit.UserService.UserUpload:input_type -> bestHabit.UserUploadRequest
	4,  // 8: bestHabit.UserService.UserUpdatePassword:input_type -> bestHabit.UserUpdatePasswordRequest
	5,  // 9: bestHabit.UserService.UserUpdateDeviceToken:input_type -> bestHabit.UserUpdateDeviceTokenRequest
	6,  // 10: bestHabit.UserService.UserUpdateProfile:output_type -> bestHabit.UserUpdateProfileResponse
	7,  // 11: bestHabit.UserService.UserUpload:output_type -> bestHabit.UserUploadResponse
	8,  // 12: bestHabit.UserService.UserUpdatePassword:output_type -> bestHabit.UserUpdatePasswordResponse
	9,  // 13: bestHabit.UserService.UserUpdateDeviceToken:output_type -> bestHabit.UserUpdateDeviceTokenResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_userservice_user_service_proto_init() }
func file_proto_userservice_user_service_proto_init() {
	if File_proto_userservice_user_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_userservice_user_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userservice_user_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Settings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userservice_user_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUpdateProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userservice_user_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userservice_user_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUpdatePasswordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userservice_user_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUpdateDeviceTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userservice_user_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUpdateProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userservice_user_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userservice_user_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUpdatePasswordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userservice_user_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUpdateDeviceTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_userservice_user_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_userservice_user_service_proto_goTypes,
		DependencyIndexes: file_proto_userservice_user_service_proto_depIdxs,
		MessageInfos:      file_proto_userservice_user_service_proto_msgTypes,
	}.Build()
	File_proto_userservice_user_service_proto = out.File
	file_proto_userservice_user_service_proto_rawDesc = nil
	file_proto_userservice_user_service_proto_goTypes = nil
	file_proto_userservice_user_service_proto_depIdxs = nil
}
